services:
  maya-app:
    build: .
    container_name: maya-platform
    ports:
      - "8501:8501"
    environment:
      - REDIS_URL=redis://host.docker.internal:6379
      - KAFKA_BROKER=host.docker.internal:9092
      - MAYA_REDIS_PREFIX=maya:dashboard
    volumes:
      - .:/app
      - /app/main_venv/
      - /app/flink_venv/
      - ./secret_data:/app/secret_data
      - ./artifacts:/app/artifacts
      - ./flink_engineered:/app/flink_engineered
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  maya-ingestor:
    build: .
    container_name: m-ingestor
    command: ["ingestor"]
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MAYA_SECRET_DATA_DIR=/app/secret_data
    volumes:
      - .:/app
      - /app/main_venv/
      - ./secret_data:/app/secret_data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
